name: CD

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 3 * * *'

jobs:
  CentOS7:
    name: CentOS 7
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for updates
        id: update_check
        continue-on-error: true
        run : |
          docker run --rm essentialkaos/centos:7 yum check-update

      - name: Trigger image rebuild
        if: ${{ steps.update_check.conclusion == 'failure' }}
        run: |
          curl -H "Content-Type: application/json" --data '{"docker_tag": "7"}' -X POST ${{ secrets.BUILD_TRIGGER_URL }}

  CentOS8:
    name: CentOS 8
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check for updates
        id: update_check
        continue-on-error: true
        run : |
          docker run --rm essentialkaos/centos:8 dnf check-update

      - name: Trigger image rebuild
        if: ${{ steps.update_check.conclusion == 'failure' }}
        run: |
          curl -H "Content-Type: application/json" --data '{"docker_tag": "8"}' -X POST ${{ secrets.BUILD_TRIGGER_URL }}
